#!/bin/sh
# mle 2014-08

# Prints all its command line arguments.
# The arguments are all enclosed in highlighted square brackets
# to avoid spacing ambiguity.

[ -n "$1" ] || exit 0

M1="[1m"
M0="[0m"

while [ -n "$1" ]; do
	echo -n "${M1}[${M0}$1${M1}]${M0} "
	shift
done

echo ""

