filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" Vundle plugins:


"Plugin 'bling/vim-airline' 
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-repeat'
Bundle 'tmhedberg/matchit'
Bundle 'dantler/vim-alternate'
Bundle 'Lokaltog/vim-easymotion'

Bundle "MarcWeber/vim-addon-mw-utils"
Bundle "tomtom/tlib_vim"
"Bundle 'garbas/vim-snipmate' 


call vundle#end()
filetype plugin indent on


" easyMotion
map \<Enter> <Plug>(easymotion-bd-w)
let g:EasyMotion_keys = 'asdghklöäqwertzuiopüyxcvbnmfj,-+'

" don't remove indentation on #-lines:
set cinkeys-=0#
set indentkeys-=0#

" show line numbers:
set number
highlight LineNr ctermfg=0 ctermbg=0 cterm=bold

" custom color scheme for PHP:
autocmd BufRead,BufNewFile *.php colorscheme mle-php

" Alt-Y shortcut for external commands.
map <ESC>y  :!
imap <ESC>y <C-O>:!

" show trailing spaces as small grey circles, show nbsp as "⎵".  (⚫,⚬)
" vim.wikia.com/wiki/Highlight_unwanted_spaces
set list
set listchars=tab:\ \ ,trail:⚬,nbsp:⎵
highlight ExtraWhitespace ctermfg=237 guifg=237
match ExtraWhitespace /\s\+$/


"""""""""""""""""""""

