"" Vim_settings:  """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

set nocompatible

" don't remove indentation on #-lines:
set cinkeys-=0#
set indentkeys-=0#
" show line numbers:
set number
" show status line with current lineno and colno:
set ruler
" show command and visual block size on status line:
set showcmd
" show current filename in terminal window title, if supported:
set title
" timeout for key combinations,
" very short timeout for terminal-based key combinations (like ESC O D)
set timeoutlen=1000
set ttimeoutlen=80
" Always show N lines around cursor when scrolling vertically:
set scrolloff=5
" nice tab-completion on command line:
set wildmenu
set wildignore=*.o,*~,*.pyc,*.bak
" more powerful backspacing:
set backspace=indent,eol,start
" automatic indenting:
set cindent
" suppress crappy ~ files:
set nobackup
" allow saving up to 1000 lines (and up to 1500 kB) in the viminfo file
set viminfo='100,<1000,s1500,:50
" allow rich colors:
set t_Co=256
" ignore case in search patterns, except...
set ignorecase
" ...if the search pattern contains upper case chars.
set smartcase



"" Load_Plugins:  """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" Vundle plugins:

	"Plugin 'bling/vim-airline'
	Bundle 'tpope/vim-surround'
	Bundle 'tpope/vim-repeat'
	Bundle 'tmhedberg/matchit'
	Bundle 'dantler/vim-alternate'
	Bundle 'Lokaltog/vim-easymotion'
	
	Bundle "MarcWeber/vim-addon-mw-utils"
	Bundle "tomtom/tlib_vim"
	"Bundle 'garbas/vim-snipmate'

call vundle#end()
filetype plugin indent on

let g:EasyMotion_keys = 'asdghklöäqwertzuiopüyxcvbnmfj,-+'


"" Colors_and_highlighting:  """""""""""""""""""""""""""""""""""""""""""""""""""

" use correct color schemes, most terminals are dark, but Vim's autodetection does not always work:
set background=dark

syntax on

hi Comment ctermfg=darkgrey
hi LineNr ctermfg=0 ctermbg=0 cterm=bold

" show trailing spaces as small grey circles, show nbsp as "⎵".  (⚫,⚬)
" vim.wikia.com/wiki/Highlight_unwanted_spaces
set list
set listchars=tab:\ \ ,trail:⚬,nbsp:⎵
highlight ExtraWhitespace ctermfg=237 guifg=237
match ExtraWhitespace /\s\+$/

" custom color scheme for PHP:
autocmd BufRead,BufNewFile *.php colorscheme mle-php


"" Shortcuts:  """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" F8: shortcut for easy clipboarding.
" Hide the line numbers, hide the space/eol/tab special characters,
" enable 'paste' mode.
map  <F8>      :set nolist nonumber paste <CR>i
imap <F8> <C-O>:set nolist nonumber paste <CR>

" F10: write, make -C current-file-directory
map  <F10>      :w<CR>:     !make -C %:p:h<CR>
imap <F10> <C-O>:w<CR><C-O>:!make -C %:p:h<CR>

" Alt_S: save shortcut
map  <ESC>s      :w<CR>
imap <ESC>s <C-O>:w<CR>

" Alt_Y: shortcut for external commands.
map  <ESC>y      :!
imap <ESC>y <C-O>:!

" Alt_Dot: special 'dot' operation
map <ESC>. .`[

" Backslash_Enter: easyMotion
map \<Enter> <Plug>(easymotion-bd-w)


"""""""""""""""""""""

